### 회원가입: HUB_DELIVERY_STAFF, COMPANY_DELIVERY_STAFF

POST localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "comstaff2",
  "password": "Pass1234!",
  "slackId": "slackId@slack.com",
  "role": "COMPANY_DELIVERY_STAFF"
}


### 회원가입: MASTER 시도 - 실패
POST localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "masstaff2",
  "password": "Pass1234!",
  "slackId": "slackId@slack.com",
  "role": "MASTER"
}

### 회원가입: HUB_MANAGER 시도 - 실패
POST localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "manstaff2",
  "password": "Pass1234!",
  "slackId": "slackId@slack.com",
  "role": "HUB_MANAGER"
}

