### 회원가입: HUB_DELIVERY_STAFF, COMPANY_DELIVERY_STAFF

POST localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "comstaff3",
  "password": "Pass1234!",
  "slackId": "slackId@slack.com",
  "role": "COMPANY_DELIVERY_STAFF"
}

### 회원가입: HUB_MANAGER

POST localhost:19091/api/auth/sign-up/hub-manager
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6Ik1BU1RFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczNDA2MDQ2NCwiZXhwIjoxNzM0MDY0MDY0fQ.p10mnWI6Jei5ptx06Eaz2jeOy89H75SpP-PORFFwI2M1ggDY27_TWavMX31LHdSCKe-U-HMaAyU78YNGpy7hHg

{
  "username": "hubman6",
  "password": "Pass1234!",
  "slackId": "slackId@slack.com",
  "role": "HUB_MANAGER"
}

### 로그인
POST localhost:19091/api/auth/sign-in
Content-Type: application/json

{
  "username": "master",
  "password": "Pass1234!"
}

### 회원 존재 여부 검증
GET localhost:19091/api/auth/verify/999
Content-Type: application/json


### 회원 정보 수정 - MASTER 권한 필요
PUT localhost:19091/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6Ik1BU1RFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczNDA2MDQ2NCwiZXhwIjoxNzM0MDY0MDY0fQ.p10mnWI6Jei5ptx06Eaz2jeOy89H75SpP-PORFFwI2M1ggDY27_TWavMX31LHdSCKe-U-HMaAyU78YNGpy7hHg

{
  "password": "New1234!",
  "slackId": "new@slack.com"
}

### 회원 정보 삭제 - MASTER 권한 필요
DELETE localhost:19091/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6Ik1BU1RFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczNDA3NDY4NCwiZXhwIjoxNzM0MDc4Mjg0fQ.Ia--LYN0MfVGV92Eb1QgsrhxykQnD_SA8VHQCNbH7v9C1HSb2rlKHoDPY83qxV0grFRWyhHkTcPnCnzGERFbWA

### 슬랙메시지를 위한 발신자, 수신자 정보
GET localhost:19091/api/users/slack-ids?senderId=1&receiverId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxMCwicm9sZSI6Ik1BU1RFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczNDIzMjU1OCwiZXhwIjoxNzM0MjM2MTU4fQ.TG-ooH6So9qkeEabyovnHITFEfGHQ6YTeqPbV-S8Pd-gPIwNN_O0WzBnhrybgRIgPKth2HEo7UskUK_JM-y0kQ
